<a href="https://colab.research.google.com/github/manjusha0109/Data-Science-Assignments-Excelr/blob/main/Elon_musk_Text_Mining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string
import re
import nltk
# pip install -U textblob
from textblob import TextBlob
from wordcloud import WordCloud
nltk.download("punkt")
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [2]:
df = pd.read_csv("Elon_musk.csv",encoding="latin-1")

In [3]:
df

Unnamed: 0                                               Text
0              1                             @kunalb11 I’m an alien
1              2  @ID_AA_Carmack Ray tracing on Cyberpunk with H...
2              3                @joerogan @Spotify Great interview!
3              4                    @gtera27 Doge is underestimated
4              5  @teslacn Congratulations Tesla China for amazi...
...          ...                                                ...
1994        1995  @flcnhvy True, it sounds so surreal, but the n...
1995        1996  @PPathole Make sure to read ur terms &amp; con...
1996        1997                @TeslaGong @PPathole Samwise Gamgee
1997        1998  @PPathole Altho Dumb and Dumber is <U+0001F525...
1998        1999                          Progress update August 28

[1999 rows x 2 columns]

In [4]:
df["Text"]

0                                  @kunalb11 I’m an alien
1       @ID_AA_Carmack Ray tracing on Cyberpunk with H...
2                     @joerogan @Spotify Great interview!
3                         @gtera27 Doge is underestimated
4       @teslacn Congratulations Tesla China for amazi...
                              ...                        
1994    @flcnhvy True, it sounds so surreal, but the n...
1995    @PPathole Make sure to read ur terms &amp; con...
1996                  @TeslaGong @PPathole Samwise Gamgee
1997    @PPathole Altho Dumb and Dumber is <U+0001F525...
1998                            Progress update August 28
Name: Text, Length: 1999, dtype: object

In [5]:
stp_words = stopwords.words("english")

In [6]:
stp_words 

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [7]:
one_tweet = df.iloc[5]['Text']

In [8]:
def TweetCleaning(tweets):
    Cleantweet=re.sub(r"@[a-zA-Z0-9]+"," ",tweets)
    Cleantweet=re.sub(r"#[a-zA-Z0-9]+"," ",Cleantweet)
    Cleantweet=''.join(word for word in Cleantweet.split() if word not in stp_words)
    return Cleantweet

In [9]:

def calPolarity(tweets):
    return TextBlob(tweets).sentiment.polarity

In [10]:
def calSubjectivity(tweets):
    return TextBlob(tweets).sentiment.subjectivity

In [11]:
def segmentation(tweets):
    if tweets > 0:
        return "positive"
    elif tweets == 0:
        return "neutral"
    else:
        return "negative"

In [12]:
df["Cleanedtweets"]=df["Text"].apply(TweetCleaning)

In [13]:
df["polarity"]=df["Cleanedtweets"].apply(calPolarity)

In [14]:
df["subjectivity"]=df["Cleanedtweets"].apply(calSubjectivity)

In [15]:
df["segmentation"]=df["polarity"].apply(segmentation)

In [16]:
pd.set_option("display.max_columns",6)

In [17]:
df.head()

Unnamed: 0                                               Text  \
0           1                             @kunalb11 I’m an alien   
1           2  @ID_AA_Carmack Ray tracing on Cyberpunk with H...   
2           3                @joerogan @Spotify Great interview!   
3           4                    @gtera27 Doge is underestimated   
4           5  @teslacn Congratulations Tesla China for amazi...   

                                       Cleanedtweets  polarity  subjectivity  \
0                                           I’malien       0.0           0.0   
1  _AA_CarmackRaytracingCyberpunkHDRnext-level.Ha...       0.0           0.0   
2                                    Greatinterview!       0.0           0.0   
3                                 Dogeunderestimated       0.0           0.0   
4  CongratulationsTeslaChinaamazingexecutionlasty...       0.0           0.0   

  segmentation  
0      neutral  
1      neutral  
2      neutral  
3      neutral  
4      neutral

In [18]:
df.pivot_table(index=['segmentation'],aggfunc={"segmentation":'count'}) #Analysis and visualization 

segmentation
segmentation              
negative                 3
neutral               1914
positive                82

In [19]:
df.sort_values(by=['polarity'],ascending=False).head(3)

Unnamed: 0                        Text Cleanedtweets  polarity  \
1594        1595  @Erdayastronaut Impressive    Impressive       1.0   
978          979            @lexfridman Nice          Nice       0.6   
1017        1018     @Carrenimfa Interesting   Interesting       0.5   

      subjectivity segmentation  
1594           1.0     positive  
978            1.0     positive  
1017           0.5     positive

In [20]:
df.sort_values(by=['polarity'],ascending=True).head(3)

Unnamed: 0                                             Text  \
852         853  @flcnhvy @NASASpaceflight @Erdayastronaut Minor   
417         418                                     @OLHZN Minor   
741         742                                @PPathole Strange   

    Cleanedtweets  polarity  subjectivity segmentation  
852         Minor     -0.05          0.20     negative  
417         Minor     -0.05          0.20     negative  
741       Strange     -0.05          0.15     negative

In [21]:
df['polarity']==0
df[df['polarity']==0].head(3)

Unnamed: 0                                               Text  \
0           1                             @kunalb11 I’m an alien   
1           2  @ID_AA_Carmack Ray tracing on Cyberpunk with H...   
2           3                @joerogan @Spotify Great interview!   

                                       Cleanedtweets  polarity  subjectivity  \
0                                           I’malien       0.0           0.0   
1  _AA_CarmackRaytracingCyberpunkHDRnext-level.Ha...       0.0           0.0   
2                                    Greatinterview!       0.0           0.0   

  segmentation  
0      neutral  
1      neutral  
2      neutral

In [22]:
df["Cleanedtweets"]

0                                                I’malien
1       _AA_CarmackRaytracingCyberpunkHDRnext-level.Ha...
2                                         Greatinterview!
3                                      Dogeunderestimated
4       CongratulationsTeslaChinaamazingexecutionlasty...
                              ...                        
1994    True,soundssurreal,negativepropagandastill&amp...
1995    Makesurereadurterms&amp;conditionsclickingaccept!
1996                                        SamwiseGamgee
1997              AlthoDumbDumber<U+0001F525><U+0001F525>
1998                               ProgressupdateAugust28
Name: Cleanedtweets, Length: 1999, dtype: object

In [23]:
text = ' '.join(df["Cleanedtweets"])
text

'I\x92malien _AA_CarmackRaytracingCyberpunkHDRnext-level.Havetriedit? Greatinterview! Dogeunderestimated CongratulationsTeslaChinaamazingexecutionlastyear.Nownextevenmore!! HappyNewYearOx!https://t.co/9WFKMYu2oj Frodounderdoge,Allthoughtwouldfail,Himselfall.https://t.co/zGxJFDzzrM _Hahathanks:) Indeed!Tweetsdefinitelyrepresentreal-worldtimeallocation. Theentertainingoutcomelikely Justsent JustagreeClubhouse https://t.co/3rWE9uHSTS It\x92sgettingreal BoughtDogecoinlilX,toddlerhodler Hedefinitelyissues,sentencingseemsbithigh Thanksfixing Pleaseunlockaccount <U+0001F923><U+0001F923> Thistruepowerhahahttps://t.co/Fc9uhQSd7O Anycryptowalletwon\x92tgiveprivatekeysavoidedcosts Yourappsucks RT:NASAselectedFalconHeavylaunchfirsttwoelementslunarGatewaytogetheronemission!https://t.co/3pWt Yes _Oncepredictcashflowreasonablywell,StarlinkIPO _Starlinkstaggeringlydifficulttechnical&amp;economicendeavor.However,https://t.co/9Z8Ac6skqx _SpaceXneedspassdeepchasmnegativecashflownextyearhttps://t.co/7J1c9

In [24]:
no_punc_text = text.translate(str.maketrans('','',string.punctuation)) # punctuation
no_punc_text

'I\x92malien AACarmackRaytracingCyberpunkHDRnextlevelHavetriedit Greatinterview Dogeunderestimated CongratulationsTeslaChinaamazingexecutionlastyearNownextevenmore HappyNewYearOxhttpstco9WFKMYu2oj FrodounderdogeAllthoughtwouldfailHimselfallhttpstcozGxJFDzzrM Hahathanks IndeedTweetsdefinitelyrepresentrealworldtimeallocation Theentertainingoutcomelikely Justsent JustagreeClubhouse httpstco3rWE9uHSTS It\x92sgettingreal BoughtDogecoinlilXtoddlerhodler Hedefinitelyissuessentencingseemsbithigh Thanksfixing Pleaseunlockaccount U0001F923U0001F923 ThistruepowerhahahttpstcoFc9uhQSd7O Anycryptowalletwon\x92tgiveprivatekeysavoidedcosts Yourappsucks RTNASAselectedFalconHeavylaunchfirsttwoelementslunarGatewaytogetheronemissionhttpstco3pWt Yes OncepredictcashflowreasonablywellStarlinkIPO StarlinkstaggeringlydifficulttechnicalampeconomicendeavorHoweverhttpstco9Z8Ac6skqx SpaceXneedspassdeepchasmnegativecashflownextyearhttpstco7J1c92hdjl AACarmackLowestcostpertoncarbonsequesterednetvalueproductmadeMusts

In [25]:
from nltk.tokenize import word_tokenize # Tokenization
text_tokens = word_tokenize(no_punc_text)
print(text_tokens[0:50])


['I\x92malien', 'AACarmackRaytracingCyberpunkHDRnextlevelHavetriedit', 'Greatinterview', 'Dogeunderestimated', 'CongratulationsTeslaChinaamazingexecutionlastyearNownextevenmore', 'HappyNewYearOxhttpstco9WFKMYu2oj', 'FrodounderdogeAllthoughtwouldfailHimselfallhttpstcozGxJFDzzrM', 'Hahathanks', 'IndeedTweetsdefinitelyrepresentrealworldtimeallocation', 'Theentertainingoutcomelikely', 'Justsent', 'JustagreeClubhouse', 'httpstco3rWE9uHSTS', 'It\x92sgettingreal', 'BoughtDogecoinlilXtoddlerhodler', 'Hedefinitelyissuessentencingseemsbithigh', 'Thanksfixing', 'Pleaseunlockaccount', 'U0001F923U0001F923', 'ThistruepowerhahahttpstcoFc9uhQSd7O', 'Anycryptowalletwon\x92tgiveprivatekeysavoidedcosts', 'Yourappsucks', 'RTNASAselectedFalconHeavylaunchfirsttwoelementslunarGatewaytogetheronemissionhttpstco3pWt', 'Yes', 'OncepredictcashflowreasonablywellStarlinkIPO', 'StarlinkstaggeringlydifficulttechnicalampeconomicendeavorHoweverhttpstco9Z8Ac6skqx', 'SpaceXneedspassdeepchasmnegativecashflownextyearhttpst

In [26]:
my_stop_words = stopwords.words("english") # Removing stopwords

In [27]:
no_stop_tokens = [word for word in text_tokens if not word in my_stop_words]
no_stop_tokens

['I\x92malien',
 'AACarmackRaytracingCyberpunkHDRnextlevelHavetriedit',
 'Greatinterview',
 'Dogeunderestimated',
 'CongratulationsTeslaChinaamazingexecutionlastyearNownextevenmore',
 'HappyNewYearOxhttpstco9WFKMYu2oj',
 'FrodounderdogeAllthoughtwouldfailHimselfallhttpstcozGxJFDzzrM',
 'Hahathanks',
 'IndeedTweetsdefinitelyrepresentrealworldtimeallocation',
 'Theentertainingoutcomelikely',
 'Justsent',
 'JustagreeClubhouse',
 'httpstco3rWE9uHSTS',
 'It\x92sgettingreal',
 'BoughtDogecoinlilXtoddlerhodler',
 'Hedefinitelyissuessentencingseemsbithigh',
 'Thanksfixing',
 'Pleaseunlockaccount',
 'U0001F923U0001F923',
 'ThistruepowerhahahttpstcoFc9uhQSd7O',
 'Anycryptowalletwon\x92tgiveprivatekeysavoidedcosts',
 'Yourappsucks',
 'RTNASAselectedFalconHeavylaunchfirsttwoelementslunarGatewaytogetheronemissionhttpstco3pWt',
 'Yes',
 'OncepredictcashflowreasonablywellStarlinkIPO',
 'StarlinkstaggeringlydifficulttechnicalampeconomicendeavorHoweverhttpstco9Z8Ac6skqx',
 'SpaceXneedspassdeepchasmnega

In [28]:
lower_words = [x.lower() for x in no_stop_tokens] # Normaliza the data
print(lower_words[0:40])

['i\x92malien', 'aacarmackraytracingcyberpunkhdrnextlevelhavetriedit', 'greatinterview', 'dogeunderestimated', 'congratulationsteslachinaamazingexecutionlastyearnownextevenmore', 'happynewyearoxhttpstco9wfkmyu2oj', 'frodounderdogeallthoughtwouldfailhimselfallhttpstcozgxjfdzzrm', 'hahathanks', 'indeedtweetsdefinitelyrepresentrealworldtimeallocation', 'theentertainingoutcomelikely', 'justsent', 'justagreeclubhouse', 'httpstco3rwe9uhsts', 'it\x92sgettingreal', 'boughtdogecoinlilxtoddlerhodler', 'hedefinitelyissuessentencingseemsbithigh', 'thanksfixing', 'pleaseunlockaccount', 'u0001f923u0001f923', 'thistruepowerhahahttpstcofc9uhqsd7o', 'anycryptowalletwon\x92tgiveprivatekeysavoidedcosts', 'yourappsucks', 'rtnasaselectedfalconheavylaunchfirsttwoelementslunargatewaytogetheronemissionhttpstco3pwt', 'yes', 'oncepredictcashflowreasonablywellstarlinkipo', 'starlinkstaggeringlydifficulttechnicalampeconomicendeavorhoweverhttpstco9z8ac6skqx', 'spacexneedspassdeepchasmnegativecashflownextyearhttpst

In [29]:
from nltk.stem import PorterStemmer # Stemming the data
ps=PorterStemmer()
stemmed_tokens = [ps.stem(word) for word in lower_words]
print(stemmed_tokens[0:10])

['i\x92malien', 'aacarmackraytracingcyberpunkhdrnextlevelhavetriedit', 'greatinterview', 'dogeunderestim', 'congratulationsteslachinaamazingexecutionlastyearnownextevenmor', 'happynewyearoxhttpstco9wfkmyu2oj', 'frodounderdogeallthoughtwouldfailhimselfallhttpstcozgxjfdzzrm', 'hahathank', 'indeedtweetsdefinitelyrepresentrealworldtimealloc', 'theentertainingoutcomelik']


In [30]:
import spacy

nlp = spacy.load("en_core_web_sm")

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [31]:
doc = nlp(' '.join(no_stop_tokens))
print(doc[0:40])

I’malien AACarmackRaytracingCyberpunkHDRnextlevelHavetriedit Greatinterview Dogeunderestimated CongratulationsTeslaChinaamazingexecutionlastyearNownextevenmore HappyNewYearOxhttpstco9WFKMYu2oj FrodounderdogeAllthoughtwouldfailHimselfallhttpstcozGxJFDzzrM Hahathanks IndeedTweetsdefinitelyrepresentrealworldtimeallocation Theentertainingoutcomelikely Justsent JustagreeClubhouse httpstco3rWE9uHSTS It’sgettingreal BoughtDogecoinlilXtoddlerhodler Hedefinitelyissuessentencingseemsbithigh Thanksfixing Pleaseunlockaccount U0001F923U0001F923 ThistruepowerhahahttpstcoFc9uhQSd7O Anycryptowalletwon’tgiveprivatekeysavoidedcosts Yourappsucks RTNASAselectedFalconHeavylaunchfirsttwoelementslunarGatewaytogetheronemissionhttpstco3pWt Yes OncepredictcashflowreasonablywellStarlinkIPO StarlinkstaggeringlydifficulttechnicalampeconomicendeavorHoweverhttpstco9Z8Ac6skqx SpaceXneedspassdeepchasmnegativecashflownextyearhttpstco7J1c92hdjl AACarmackLowestcostpertoncarbonsequesterednetvalueproductmadeMustscalableght

In [32]:
lemmas = [token.lemma_ for token in doc]
print(lemmas[0:25])


['I\x92malien', 'AACarmackRaytracingCyberpunkHDRnextlevelHavetriedit', 'Greatinterview', 'dogeunderestimate', 'CongratulationsTeslaChinaamazingexecutionlastyearNownextevenmore', 'HappyNewYearOxhttpstco9WFKMYu2oj', 'FrodounderdogeAllthoughtwouldfailHimselfallhttpstcozGxJFDzzrM', 'Hahathanks', 'IndeedTweetsdefinitelyrepresentrealworldtimeallocation', 'theentertainingoutcomelikely', 'Justsent', 'JustagreeClubhouse', 'httpstco3rWE9uHSTS', 'It\x92sgettingreal', 'BoughtDogecoinlilXtoddlerhodler', 'Hedefinitelyissuessentencingseemsbithigh', 'Thanksfixing', 'Pleaseunlockaccount', 'u0001f923u0001f923', 'thistruepowerhahahttpstcofc9uhqsd7o', 'anycryptowalletwon\x92tgiveprivatekeysavoidedcost', 'yourappsuck', 'rtnasaselectedfalconheavylaunchfirsttwoelementslunargatewaytogetheronemissionhttpstco3pwt', 'yes', 'oncepredictcashflowreasonablywellstarlinkipo']


In [33]:
from sklearn.feature_extraction.text import CountVectorizer # Feature Extraction
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(stemmed_tokens)

pd.DataFrame.from_records([vectorizer.vocabulary_]).T.sort_values(0,ascending=False).head(20)

print(vectorizer.vocabulary_)

print(vectorizer.get_feature_names()[50:100])
print(X.toarray()[50:100])

print(X.toarray().shape)

{'malien': 846, 'aacarmackraytracingcyberpunkhdrnextlevelhavetriedit': 41, 'greatinterview': 528, 'dogeunderestim': 344, 'congratulationsteslachinaamazingexecutionlastyearnownextevenmor': 298, 'happynewyearoxhttpstco9wfkmyu2oj': 558, 'frodounderdogeallthoughtwouldfailhimselfallhttpstcozgxjfdzzrm': 478, 'hahathank': 552, 'indeedtweetsdefinitelyrepresentrealworldtimealloc': 699, 'theentertainingoutcomelik': 1696, 'justsent': 763, 'justagreeclubhous': 754, 'httpstco3rwe9uhst': 603, 'it': 719, 'sgettingr': 1397, 'boughtdogecoinlilxtoddlerhodl': 225, 'hedefinitelyissuessentencingseemsbithigh': 570, 'thanksfix': 1665, 'pleaseunlockaccount': 1071, 'u0001f923u0001f923': 1896, 'thistruepowerhahahttpstcofc9uhqsd7o': 1778, 'anycryptowalletwon': 146, 'tgiveprivatekeysavoidedcost': 1660, 'yourappsuck': 2111, 'rtnasaselectedfalconheavylaunchfirsttwoelementslunargatewaytogetheronemissionhttpstco3pwt': 1231, 'ye': 2053, 'oncepredictcashflowreasonablywellstarlinkipo': 1026, 'starlinkstaggeringlydifficu

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [34]:
vectorizer_ngram_range=CountVectorizer(analyzer='word',ngram_range=(1,3),max_features=(100)) # bigram and trigram
bow_matrix_ngram = vectorizer_ngram_range.fit_transform(df["Cleanedtweets"])

bow_matrix_ngram 

print(vectorizer_ngram_range.get_feature_names())
print(bow_matrix_ngram.toarray())

['0001f1e9', '0001f1e9 0001f1ea', '0001f1ea', '0001f339', '0001f3b6', '0001f440', '0001f44d', '0001f495', '0001f4af', '0001f525', '0001f525 0001f525', '0001f5a4', '0001f600', '0001f609', '0001f680', '0001f923', '0001f923 0001f923', '0435', '043b', '043e', '100', '200d', '2192', '2192 https', '2192 https co', '2660', '2660 fe0f', '26a1', '26a1 fe0f', '_enoughyes', 'absolutely', 'agreed', 'also', 'amp', 'amp https', 'amp https co', 'buhttps', 'buhttps co', 'but', 'can', 'co', 'comingsoon', 'cool', 'doesn', 'doge', 'don', 'exactly', 'falcon9', 'fe0f', 'forsure', 'goodanalysis', 'goodpoint', 'greatgame', 'gt', 'haha', 'hahatrue', 'hopefully', 'however', 'https', 'https co', 'indeed', 'it', 'liftoff', 'liftoff https', 'liftoff https co', 'long', 'lt', 'no', 'notbad', 'ok', 'prettymuch', 'rt', 'rt falcon9', 'rt https', 'rt https co', 'rt liftoff', 'rt liftoff https', 'rt_crew', 'shttps', 'shttps co', 'sigh', 'sorry', 'spacex', 'sure', 'technically', 'term', 'tesla', 'thankyou', 'that', 'the'

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer # TFidf vectorizer 
vectorizer_n_gram_range_max_features = TfidfVectorizer(analyzer="word",ngram_range=(1,3),max_features=10)
tf_idf_matrix_n_gram_max_features = vectorizer_n_gram_range_max_features.fit_transform(df["Cleanedtweets"])

print(vectorizer_n_gram_range_max_features.get_feature_names())
print(tf_idf_matrix_n_gram_max_features.toarray())

['0001f923', '0001f923 0001f923', 'amp', 'co', 'https', 'https co', 'it', 'rt', 'we', 'yes']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [36]:
import matplotlib.pyplot as plt # wordcloud
%matplotlib inline
from wordcloud import WordCloud,STOPWORDS

In [39]:
def plot_cloud(wordcloud): # Define a function to plot word cloud
    plt.figure(figsize=(15,30))
    plt.imshow(wordcloud)
    plt.axis("off");

wordcloud = WordCloud(width= 3000, height=2000, background_color="black", max_words=100, colormap="Set2").generate(text)